### ISSUE TITLE
Compatibility with japanese text

### ISSUE THREAD

**Issue by damiansh** [shinkiseki/MorePortraitsInZero#11]
I tried the mod and it wasn't working, and then I realized that maybe because I was playing the game with text in Japanese. I switched it to english and the added portraits started to appear. 

Is there a way to make it compatible if you are playing with jp text? 

I understand if not or it is more trouble than what it is worth. I just wanted to try and ask here just in case.  Thanks for the hard work!

**Comment by damiansh** [comment]
Sorry, I did not see the other issue where you are already working on it, thanks!

**Comment by shinkiseki** [comment]
Hello! Yeah, adding support for the JP text basically requires building the entire mod again. Especially with Azure coming out soon, this is considered a low priority that I'm not working on at the moment, so please don't sit around waiting for it.

However, I agree that it'd be a great long-term feature, and if there's enough interest, I'll reprioritize it accordingly!
