### ISSUE TITLE
Kate's Portrait not showing

### ISSUE THREAD

**Issue by XanoPhobious** [shinkiseki/MorePortraitsInZero#16]
Just to let you know: your own mod shows Kate's Portrait; however, if I also apply the latest version of "Inevitable-Zero" it will not.

**Comment by Kyuuhachi** [comment]
That's because I've been slacking. I'll try to get it done asap.

**Comment by XanoPhobious** [comment]
> That's because I've been slacking. I'll try to get it done asap.

Oh, I was about to let you know on your mod page.
Thank you, I'll be waiting.

**Comment by Kyuuhachi** [comment]
New versions up. Should've done that weeks ago... procrastination is a bitch.

**Comment by shinkiseki** [comment]
Thanks for taking care of that, Kyuuhachi!

For issues regarding Inevitable Zero/Azure Vitality, please refer to Kyuuhachi's GitHub pages for those projects.
