### ISSUE TITLE
Kate's portrait only showing since Chapter 1, Day 2.

### ISSUE THREAD

**Issue by DolphinIsNotaFish** [shinkiseki/MorePortraitsInZero#17]
As the title says. I can't guarantee that I talked to Kate in every instances before Chapter 1, Day 2, but all the occasions that I did had no portrait of her.

These include:

**Prologue, Day 3, Morning - Crossbell Police Department**
> Whoa... Is that you, Lloyd? Long time no see!
> Oh, yeah. I had a ton of fun showing Lloyd the ropes. No matter what you threw at him, he'd always pick it up lightning fast.
> You know...that division you were assigned to is quite a bit unorthodox. I'll admit, it's got me a little worried...
> But don't forget: Good things come to those who work hard. I'm sure it'll pay off.
> All righty, then. Time to whip these rookies into shape!
> Oh. In case you didn't know, we're a part of the Metropolitan Division.
> Our main duty is to patrol the city, so I'll be out and about quite a bit. I hope we bump into each other again!

**Prologue, Day 3, Noon - Crossbell Police Department**
> Phew, I'm glad we were able to get the rookies this year on their way.
> All right, now I've just got to draw up a report for the chief.

**Chapter 1, Day 1, Morning - Crossbell Police Department**
> Let's see... Here's the roster sheets, and...
> We were supposed to use the meeting room upstairs, but the First Division went and took it for themselves.
> Those guys always do whatever they want. It's like the rest of us might as well not even be here.

**Chapter 1, Day 1, Noon - Crossbell Police Department**
> Officer, please. Spare the the 'veteran' title.
> It makes me sound so old.
> Let me take a look... There's been more orbal vehicles on the road, so I think I'll go to Central Square.
> I am a veteran, after all!

The next day (**Chapter 1, Day 2, Morning - Central Square**) shows Kate's portrait as normal.

These are what I could check from the save files I keep. I hope it helps!

**Comment by shinkiseki** [comment]
Okay, thanks for catching this issue! I appreciate your thoroughness with feedback, as this made it easier to identify the problem. I forgot to update the file belonging to the Crossbell Police Department, so the newly added Kate portraits weren't showing up. I've fixed this in v1.3.1.

Please let me know if you run into any other issues!
