### ISSUE TITLE
[Bug] Game stuck after talking to scott

### ISSUE THREAD

**Issue by Findns** [shinkiseki/MorePortraitsInZero#6]
This is during the Intermission, when walking KeA around town. After talking to Scott and his fiancee in the harbor district, the game stops responding to any input. Music still plays fine. Maybe it has to do with the dialogue and the "heart" bubbles displayed afterwards?

Attached savefile if needed.
[SAV0002.zip](https://github.com/shinkiseki/MorePortraitsInZero/files/9793220/SAV0002.zip)

**Comment by shinkiseki** [comment]
Hello! Thanks for posting this issue. I took a look through your save file (nice choice of Randy), but I couldn't replicate the issue that you encountered -- I was able to talk to Scott + Pearl and then continue controlling the SSS as usual. I tried talking to them again, as well as talking to the other NPCs in the area, all without any soft-locking that you encountered.

Was this a repeatable bug? Or did you find some way to get around this issue?

**Comment by Findns** [comment]
Thanks for the investigation :)
It's 100% reproducible for me yes... I had another soft lock a bit after, when exiting the church after talking to Sister Marbles.
I'm using an old Geofront version of the game though, maybe that's why 🤷

**Comment by shinkiseki** [comment]
Ah, that's probably the reason. This mod is not compatible with Geofront Zero.

I do have a complete version of this mod for Geofront Zero, so you're welcome to use that! Link is in the description: https://www.youtube.com/watch?v=gPqF-cjxZ3c
