### ISSUE TITLE
Funky line break for Mireille 

### ISSUE THREAD

**Issue by Lennyoh** [shinkiseki/MorePortraitsInZero#8]
A dialogue box from Mireille in chapter 3 gets handled in a funky way
![20221221003902_1](https://user-images.githubusercontent.com/84484024/209215851-05b2601d-041c-44cb-83d3-b3402caf3dfb.jpg)

**Comment by shinkiseki** [comment]
Thanks for catching this! I've released a new version (v1.0.2) that should solve this issue.

I'm gonna close this issue -- let me know if this issue remains unresolved and I'll reopen it.
